Enable: true
 
Message:
 IsPlayer: "--\nThis &dis \n&aAn &6Exemple \nof &5a &8custom \n&cMOTD &afor &4PLAYER!\n--"
 IsStaff: "--\nThis &dis \n&aAn &6Exemple \nof &5a &8custom \n&cMOTD &afor &4Staff!\n--"